### ISSUE TITLE
Install Error - Next steps?

### ISSUE THREAD

**Issue by SebastienViel** [dcmeglio/hubitat-packagemanager#106]
I completed an install with error - I want to ensure the right person knows about the error, but am not sure who should be notified and how.

Would it be possible, if this is not occurring already, that the error condition also automatically send a note to the owner of the problematic app if that is what is required?  Also, a message could be added to the error indicating that the package owner has been notified.

Otherwise, it would add value to add the process the the user should follow in case of error, as part of the error message.

FYI, the error message that I got in this case was:

Error Occurred During Installation
An error occurred while installing the package: Failed to upgrade app https://raw.githubusercontent.com/bptworld/Hubitat/master/Apps/Tile%20Master/TM2-child.groovy.

**Comment by dcmeglio** [comment]
It doesn't send a note to the app owner and that's not something I really want to do. Imagine for a moment if this catches on and HE grows. What developer is going to want wake up to 1,200 emails saying there was an issue? It would require building a server based solution to check if the particular issue was already reported, etc. or building a Telemetry system like Microsoft and Google have (things like crashlytics) which get really complicated. I think if I were to just start emailing developers every time a user encountered an issue people devs would abandon the system. Remember, HE developers are doing this for fun, not professionally. Sometimes I take 2 weeks to get to looking at a bug because work is busy. I wouldn't want 2 weeks worth of error reports :) 

In this situation, HE made a change and it broke a bunch of apps so it kind of all hit the fan at once (including HPM itself breaking!)

I could certainly make it show a message saying "error with app blah blah blah please contact DEV NAME" as a middle ground idea.

**Comment by SebastienViel** [comment]
Yea, I totally get it!  Message shown to the user may be the best idea.

**Comment by dcmeglio** [comment]
Better error messaging has been added to 1.5.0

**Comment by SebastienViel** [comment]
Awesome!  😁
