### ISSUE TITLE
A couple UI suggestions -categories

### ISSUE THREAD

**Issue by neonturbo** [dcmeglio/hubitat-packagemanager#107]
Some of these categories are getting crowded, namely "Integrations".  And I always struggle with what is "Control" vs "Convenience" or "Utility". I almost always have to dig through all of them to find what I want. 

I am not sure how to clean this up, but one suggestion that would be a fairly straightforward fix would be to divide the integrations into cloud based vs drivers. I.E. Bryan Copeland's Zwave drivers aren't the same as an API based integration.

I think the names of categories need some changes to more clearly define them, but I am sure that would really mess things up at this point. Maybe the following would help that though.

I would suggest, that if you are going to keep the existing category names, that maybe a description of each one be added to the "Install a Package from a Repository", "Choose a category "  selection menu items. (Control, Integrations, Utility etc).  So instead of _Control_, it would say _Control - Thermostats, Blinds, Switches_  or something like that. It seems like that would help the developers choose a category as well as a user finding the correct category easier.

**Comment by dcmeglio** [comment]
In hindsight I HATE the categories. If I had a way to do the searching from the get-go I'd have done that only. I don't know how old you are, but back in the day sites like yahoo used to try to have all websites on the internet in categories. It quickly became a mess and you never knew where to go to find anything. And that's why we all just search now a days...

The reality is developers can use whatever categories they want. It was kind of an "honor system" to use the ones I put out there, so changing it is actually super easy. It just requires the developers to specify a different word. I agree though, I'm going to propose more be added and I like your suggestions in general

**Comment by neonturbo** [comment]
I am probably older than you think, I remember pre-search days on the net, usenet and all that. Also I remember Netscape _Navigator_ (pre-Mozilla!) I think I even have a copy of it somewhere on a 3.5" floppy. LOL

**Comment by dcmeglio** [comment]
Based on the community feedback I've added a bunch of new categories (discussed on the forum) and also the ability to define a secondary category for a package. This will be included in 1.5.0
