### ISSUE TITLE
To all the developers on the Hubitat platform

### ISSUE THREAD

**Issue by codahq** [dcmeglio/hubitat-packagemanager#118]
Last night I made this statement:

https://community.hubitat.com/t/z-wave-storms-looks-like-he-hubs-fault/46176/59

Today I am banned.  Read it through.  Tell me why it warrants a ban.  Then decide based on that answer if this is really the company you want to be dedicating your time and talents towards.

**Comment by dcmeglio** [comment]
Hubitat is a product. It's a product I purchased. It's no different than any other appliance I own. I am not "dedicated" to it by any means. It currently meets my needs. If it continues to meet my needs, I will continue to use it. If it fails to meet my needs, it'll end up with my SmartThings when it stopped meeting my needs,  in the trash can. If you're unhappy with it just do like you said, move on to something else. 

Hubitat is a for profit company. It's not a forum for free speech. If they want to ban you because your username had the letter "a" in it, they can. I've bought products from companies that are far worse. Hell, Apple, Google, and any other big hardware manufacturer has been accused of child labor, slavery, price fixing, sabotage, etc. Not good stuff. In the grand scheme of things, them deciding the type of speech they want on their product forum and perhaps banning a user doesn't really get me riled up. If Hubitat no longer meets your needs, use one of the other competing products. You're a smart guy and I know you're more than capable of getting any of the other platforms up and running.

The fact is, it works for me. I'm not on a crusade to make sure it works for every other consumer out there. If it does have Z-Wave issues for others, honestly, it's not my problem. At the end of the day mine is fine with nearly 80 Z-Wave devices. I feel bad for those affected by a possible bug, but it's really no harm done to me. I will continue to use it and to make tools that make my own experience with it better. I don't see any reason to do anything different.

I'm not looking to get into a "whose right?" debate. Would I have banned you? No. But you know what? I also wouldn't have pulled all my code that other people were using off of github because of a disagreement. So I don't really agree with either side here. I will keep using the product and building solutions for it for as long as it suits my needs and I find it interesting. If that changes, then I'll move on to something better. I'm a capitalist. Right now it's the best product I've found. If a day comes that it isn't, I vote my my wallet.

**Comment by codahq** [comment]
If you calling the reason I pulled support for Hubitat a "disagreement" then you haven't been paying attention or don't care to.

This is not a "who's right" debate and the "mine is fine" excuse is poor.  Given the current climate I hope you try that with the important political and social movements and initiatives and see how that flies.  There is somebody worse is a poor excuse.  Have a backbone.

And if you have a problem with me pulling my code then you're a hypocrite, aren't you?  If you can vote with your wallet why can't I vote with my wallet or my time or my talents?  Have you really drank the koolaid this deeply?

**Comment by dcmeglio** [comment]
Please use the issues on this package to report issues with this package.
