### ISSUE TITLE
Fatal error setting update time in 1.2.1

### ISSUE THREAD

**Issue by draperw** [dcmeglio/hubitat-packagemanager#75]
I'm getting the following when trying to set update time:

app:28982020-04-25 10:10:45.090 am errorjava.text.ParseException: Unparseable date: "12:00AM" on line 89 (prefSettings)

**Comment by dcmeglio** [comment]
A couple questions. What browser are you using? Could you provide a screenshot of what you typed in? Hubitat should only be allowing you to enter valid values. I believe a space is required before the AM but I'm unsure how you managed to do it that way since I set the field to a "time" field which means HE should validate it.

**Comment by draperw** [comment]
Safari on MacOS. This error is reproducible. The issue is that by default the minutes field is blank. If I change it to 00 then no issues.

**Comment by draperw** [comment]
Here is a screen shot
<img width="529" alt="Screen Shot 2020-04-26 at 11 37 44 AM" src="https://user-images.githubusercontent.com/28066333/80313773-cbb84100-87b2-11ea-8a2a-3a7ed0202095.png">

**Comment by dcmeglio** [comment]
That control is rendered by Hubitat. I will submit it to HE because I don't think there is anything I can do about it.

**Comment by dcmeglio** [comment]
What's your username on the HE forum? I'd like to tag you just in case they have any follow up questions (I don't own a Mac)

**Comment by draperw** [comment]
bill.d
